### ISSUE TITLE
Relation to multiple tables

### ISSUE THREAD

**Issue by ghost** [WebAssembly/call-tags#2]
An application could have an internal and external function table, one that it reserves for internal access, and one that it exports, containing functions that it is "okay" with other modules calling and using.

How does, or doesn't having multiple tables solve the problem that this proposal is attempting to solve?

**Comment by RossTate** [comment]
The structure you describe pertains to the problem of restricting dynamic access to functions from other modules, which is also one problem this proposal pertains to. The two approaches to this problem seem to have tradeoffs:
* Using two tables still requires whole-program reasoning to determine which functions are dynamically accessible outside the module. Call tags can alternatively let you use one table but have two tags&mdash;one exported, one not&mdash;and by looking at which tag(s) are associated with which functions you can easily determine which functions are dynamically accessible outside the module.
* On the other hand, with two tables it is possible for the module to dynamically change which functions are externally accessible and which are not, which call tags cannot do.

**Comment by ghost** [comment]
Thanks for the explanation! It helped me wrap my head around what call tags are getting at.
